# TODO: Use these strictly in development (extend from production config)

# JS Shell Docker Compose Development Configuration

# TODO: Autorestart all environments in production

version: '3.3'

networks:
  # Establish base network to resolve container hostnames (esp. w/ Nginx)
  # @see https://github.com/docker/compose/issues/3412#issuecomment-472323332
  shell-core-service-network:

services:
  # Enables proxying to host machine w/o depending on host network binding
  # (network_mode: host), which are not available using custom networks
  dockerhost:
    # TODO: Fork this to https://github.com/zenOSmosis
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    networks:
      - shell-core-service-network
  
  # Creates a self-signed SSL proxy for local development
  # This permits access to media devices (e.g. microphone / camera) during
  # development
  # 
  # This is not intended to run on a production web server
  # (use https://github.com/linuxserver/docker-letsencrypt instead)
  dev_proxy:
    # build: https://github.com/zenOSmosis/docker-dev-ssl-proxy.git
    build: ./docker_modules/dev-ssl-proxy
    # restart: always
    depends_on:
      - backend
    networks:
      - shell-core-service-network
    volumes:
      - ./docker_modules/dev-ssl-proxy:/app # Only during development
    environment:
      PROXY_ADDRESS: http://backend:3001 # Important, don't use quotations
      # here, or it may break the template
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./backend
    # restart: always
    depends_on:
      - redis
      - mongo
    volumes:
      - /tmp:/tmp # Only during development
      - ./:/shell # Only during development
    environment:
      NODE_ENV: development
      TERM: xterm # Enables interactive CLI environments
      BACKEND_REDIS_HOST: redis # TODO: Rename to REDIS_HOSTNAME
      BACKEND_REDIS_PORT: 6379  # TODO: Rename to REDIS_PORT
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      MONGO_SHELL_DB_NAME: dev_shell
      MONGO_SHELL_USERNAME: shellusername
      MONGO_SHELL_PASSWORD: shellpassword
    user: ${UGID}
    command: ["npm", "run", "start:dev"]
    privileged: true # Only during development or special deployments
    cap_add:
      - SYS_ADMIN # Only during development or special deployments
      - NET_ADMIN # Only during development or special deployments
    networks:
      - shell-core-service-network
    # Only during development or special deployments
    # Note: Note: These options are ignored when deploying a stack in swarm
    # mode with a (version 3) Compose file.
    # @see https://docs.docker.com/compose/compose-file/
    expose:
      - 3001
  
  # @see https://codewithhugo.com/setting-up-express-and-redis-with-docker-compose/
  redis:
    image: redis
    # restart: always
    networks:
      - shell-core-service-network
    expose:
      - 6379
  
  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_SHELL_DB_NAME: dev_shell
      MONGO_SHELL_USERNAME: shellusername
      MONGO_SHELL_PASSWORD: shellpassword
    volumes:
      - ./scripts/mongo.init:/docker-entrypoint-initdb.d
    networks:
      - shell-core-service-network
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    # restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_SITE_BASEURL: /mongo-express
    networks:
      - shell-core-service-network
    expose:
      - 8081

  # searx:
  #  build: ./docker_modules/searx
  #  networks:
  #    - shell-core-service-network
  #  expose:
  #    - 8080

  # Note: No direct network access to frontend; proxied through backend
  frontend:
    build: ./frontend
    # restart: always
    depends_on:
      - backend
    volumes:
      # Backend is mapped w/ frontend because of shared object in utils/bind
      - ./:/shell # Only during development
    environment:
      NODE_ENV: development
      REACT_APP_PROJECT_NAME: Shell Desktop
      REACT_APP_WEB_RTC_USERNAME: username
      REACT_APP_WEB_RTC_PASSWORD: password
      # - HTTPS=true
    networks:
      - shell-core-service-network
    command: ["npm", "run", "start"]
    expose:
      - 3000
    user: ${UGID}
   
  # TODO: Use environment variable w/ username / password
  coturn:
    build: ./docker_modules/docker-coturn
    networks:
     - shell-core-service-network
    volumes:
      - ./docker_modules/docker-coturn:/app # Only during development
    environment:
      USERNAME: username
      PASSWORD: password
      REALM: realm
    ports:
      - 3478:3478
      - 3478:3478/udp
      - 65435-65535:65435-65535/udp